In [1]:
#importing numpy and calling as an alias called np
import numpy as np

* numpy - numerical python
* most commonly used python library
* using for array manipulation
* easy to operate for large multidimensional arrays

In [2]:
#eg:
x=np.array([1,2,3])   # 1-D array or a vector
x

array([1, 2, 3])

In [3]:
x=np.array([[1,2,3],[4,5,6]])  # 2-D array 
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(x)        #type

numpy.ndarray

# Operations (+,-,*,/)

In [7]:
#addition
#corresponding elements will add
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [8]:
a=np.array([1,2,3])
a*3

array([3, 6, 9])

In [9]:
#scaling and translation
a=np.array([[1,2],[3,4]])
a*2+1

array([[3, 5],
       [7, 9]])

# Transpose of matrix

In [11]:
x=np.array([[1,2,3],[4,5,6]])
print('x: ',x)
print('shape of x: ',x.shape)
y=x.T
print('transpose of x, y: ',y)
print('shape of transpose x ,y shape :',y.shape)

x:  [[1 2 3]
 [4 5 6]]
shape of x:  (2, 3)
transpose of x, y:  [[1 4]
 [2 5]
 [3 6]]
shape of transpose x ,y shape : (3, 2)


In [12]:
#however , transpose operation does not affect 1-D
#eg
a=np.array([1,2,3,4])
a.T

array([1, 2, 3, 4])

In [14]:
#but will happen on 1D array with 2 brackets
#eg
b=np.array([[1,2,3,4]])
b.T

array([[1],
       [2],
       [3],
       [4]])

# Norm of an array

In [15]:
x=np.array([1,2,3,4])
np.linalg.norm(x)

5.477225575051661

In [16]:
#norm of 2D array
x=np.array([[1,2],[3,4]])
np.linalg.norm(x)

5.477225575051661

In [17]:
#norm through axis
x=np.array([[1,2,3],[4,5,6]])
print('norm throgh x-axis :',np.linalg.norm(x,axis=1))
print('norm throgh y-axis :',np.linalg.norm(x,axis=0))

norm throgh x-axis : [3.74165739 8.77496439]
norm throgh y-axis : [4.12310563 5.38516481 6.70820393]


# Dot Product

3 ways

In [20]:
#1 - normal way
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.dot(a,b)

70

In [21]:
#2
np.sum(a*b)

70

In [23]:
#3
sum=0
for i,j in zip(a,b):
  sum +=i*j
print(sum)

70


In [25]:
#sum over axis
a= np.array([[1,2],[3,4],[5,6]])
print('x-axis sum :',np.sum(a,axis=1))
print('y-axis sum :',np.sum(a,axis=0))


x-axis sum : [ 3  7 11]
y-axis sum : [ 9 12]


In [26]:
#mean over axis
a= np.array([[1,2],[3,4],[5,6]])
print('x-axis mean :',np.mean(a,axis=1))
print('y-axis mean :',np.mean(a,axis=0))

x-axis mean : [1.5 3.5 5.5]
y-axis mean : [3. 4.]


In [29]:
#another representation for sum and mean
a=np.array([1,2,3])
print(a.sum())
print(a.mean())

6
2.0
